name: runner stop

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      # label: 
      #   required: true
      #   default: '${{ jobs.start-runner.outputs.label }}'
      #   type: string
      # ec2-instance-id: 
      #   required: true
      #   default:
      #   type: string

jobs:
  stop-runner:
    # needs:
    #   - start-runner # required to get output from the start-runner job
    #   - environment # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ secrets.CICD_OIDC_ROLE }}
          role-session-name: cicd-role-session
          mask-aws-account-id: false

      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
