name: runner stop

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      label: 
        required: true
        type: string
      ec2-instance-id: 
        required: true
        type: string
    secrets:
      role-to-assume:
        required: true
      github-token:
        required: true

jobs:
  stop-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ secrets.role-to-assume }}
          role-session-name: gh-ephemeral-runner-role-session
          mask-aws-account-id: false

      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.github-token }}
          label: ${{ inputs.label }}
          ec2-instance-id: ${{ inputs.ec2-instance-id }}
